package io.snice.codecs.codec.diameter.avp;

import java.util.Optional;

/**
 * Should be autogenerated - will get to it.
 */
public enum Vendor {
   NONE(0L, "None"),
   MERIT(61L, "Merit Networks"),
   USR(429L, "US Robotics Corp."),
   LUCENT(1751L, "Lucent Technologies"),
   DEUTSCHE_TELEKOM_AG(2937L, "Deutsche Telekom AG"),
   ACISION(3830L, "Acision"),
   SKT(5806L, "SK Telecom"),
   TGPP(10415L, "3GPP"),
   ETSI(13019L, "ETSI"),
   TANGO(13421L, "Tango Telecom Limited"),
   CHINATELECOM(81000L, "China Telecom"),
   TGPPCX(16777216L, "3GPP CX/DX");

   private final long code;
   private final String friendlyName;

   Vendor(final long code, final String friendlyName) {
      this.code = code;
      this.friendlyName = friendlyName;
   }

   public static Optional<Vendor> getValue(final String name) {
      for (final Vendor v : values()) {
         if (v.toString().replace("_", "").equalsIgnoreCase(name)) {
            return Optional.of(v);
         }
      }

      return Optional.empty();
   }

   public static Optional<Vendor> getValue(final long value) {
      for (final Vendor v : values()) {
         if (v.code == value) {
            return Optional.of(v);
         }
      }

      return Optional.empty();
   }


   public long getCode() {
      return code;
   }

   public String getFriendlyName() {
      return friendlyName;
   }
}
