package io.snice.codecs.codec.diameter.avp.api;


import io.snice.buffer.Buffer;
import io.snice.buffer.Buffers;
import io.snice.codecs.codec.diameter.avp.Avp;
import io.snice.codecs.codec.diameter.avp.AvpMandatory;
import io.snice.codecs.codec.diameter.avp.AvpParseException;
import io.snice.codecs.codec.diameter.avp.AvpProtected;
import io.snice.codecs.codec.diameter.avp.FramedAvp;
import io.snice.codecs.codec.diameter.avp.Vendor;
import io.snice.codecs.codec.diameter.avp.impl.DiameterIdentityAvp;
import io.snice.codecs.codec.diameter.avp.type.DiameterIdentity;

import static io.snice.preconditions.PreConditions.assertNotNull;

/**
 * This is an autogenerated class - do not edit
 * 
 */
public interface DestinationRealm extends Avp<DiameterIdentity> {

    int CODE = 283;

    
    static DestinationRealm of(final Buffer value) {
        final DiameterIdentity v = DiameterIdentity.parse(value);
        return of(v);
    }

    static DestinationRealm of(final String value) {
        return of(Buffers.wrap(value));
    }

    
    

    static DestinationRealm of(final DiameterIdentity value) {
        assertNotNull(value);
        final Builder<DiameterIdentity> builder =
                Avp.ofType(DiameterIdentity.class)
                        .withValue(value)
                        .withAvpCode(CODE)
                        .isMandatory(AvpMandatory.MUST.isMandatory())
                        .isProtected(AvpProtected.MUST_NOT.isProtected())
                        .withVendor(Vendor.NONE);

        return new DefaultDestinationRealm(builder.build());
    }

    @Override
    default long getCode() {
        return CODE;
    }

    default boolean isDestinationRealm() {
        return true;
    }

    @Override
    default DestinationRealm toDestinationRealm() {
        return this;
    }

    static DestinationRealm parse(final FramedAvp raw) {
        if (CODE != raw.getCode()) {
            throw new AvpParseException("AVP Code mismatch - unable to parse the AVP into a " + DestinationRealm.class.getName());
        }
        return new DefaultDestinationRealm(raw);
    }

    class DefaultDestinationRealm extends DiameterIdentityAvp implements DestinationRealm {
        private DefaultDestinationRealm(final FramedAvp raw) {
            super(raw);
        }

        @Override
        public DestinationRealm ensure() {
            return this;
        }

        @Override
        public boolean equals(final Object other) {
            if (this == other) {
                return true;
            }

            if (other == null) {
                return false;
            }

            try {
                final DestinationRealm o = (DestinationRealm)((FramedAvp)other).ensure();
                final DiameterIdentity v = getValue();
                return v.equals(o.getValue());
            } catch (final ClassCastException e) {
                return false;
            }
        }
    }
}
