package io.snice.networking.codec.diameter.avp.api;

import io.snice.buffer.Buffer;
import io.snice.buffer.Buffers;
import io.snice.networking.codec.diameter.avp.Avp;
import io.snice.networking.codec.diameter.avp.AvpMandatory;
import io.snice.networking.codec.diameter.avp.AvpParseException;
import io.snice.networking.codec.diameter.avp.AvpProtected;
import io.snice.networking.codec.diameter.avp.FramedAvp;
import io.snice.networking.codec.diameter.avp.Vendor;

import io.snice.networking.codec.diameter.avp.impl.DiameterUnsigned32Avp;
import io.snice.networking.codec.diameter.avp.type.Unsigned32;

/**
 * This is an autogenerated class - do not edit
 * 
 */
public interface AcctApplicationId extends Avp<Unsigned32> {

    int CODE = 259;

    
    static AcctApplicationId of(final Buffer value) {
        final Unsigned32 v = Unsigned32.parse(value);
        final Builder<Unsigned32> builder =
                Avp.ofType(Unsigned32.class)
                        .withValue(v)
                        .withAvpCode(CODE)
                        .isMandatory(AvpMandatory.MUST.isMandatory())
                        .isProtected(AvpProtected.MUST_NOT.isProtected())
                        .withVendor(Vendor.NONE);

        return new DefaultAcctApplicationId(builder.build());
    }

    static AcctApplicationId of(final String value) {
        return of(Buffers.wrap(value));
    }
    

    @Override
    default long getCode() {
        return CODE;
    }

    default boolean isAcctApplicationId() {
        return true;
    }

    default AcctApplicationId toAcctApplicationId() {
        return this;
    }

    static AcctApplicationId parse(final FramedAvp raw) {
        if (CODE != raw.getCode()) {
            throw new AvpParseException("AVP Code mismatch - unable to parse the AVP into a " + AcctApplicationId.class.getName());
        }
        return new DefaultAcctApplicationId(raw);
    }

    class DefaultAcctApplicationId extends DiameterUnsigned32Avp implements AcctApplicationId {
        private DefaultAcctApplicationId(final FramedAvp raw) {
            super(raw);
        }
    }
}
