package io.snice.networking.codec.diameter.avp.api;

import io.snice.buffer.Buffer;
import io.snice.buffer.Buffers;
import io.snice.networking.codec.diameter.avp.Avp;
import io.snice.networking.codec.diameter.avp.AvpMandatory;
import io.snice.networking.codec.diameter.avp.AvpParseException;
import io.snice.networking.codec.diameter.avp.AvpProtected;
import io.snice.networking.codec.diameter.avp.FramedAvp;
import io.snice.networking.codec.diameter.avp.Vendor;

import static io.snice.preconditions.PreConditions.assertNotNull;

import io.snice.networking.codec.diameter.avp.impl.DiameterIdentityAvp;
import io.snice.networking.codec.diameter.avp.type.DiameterIdentity;

/**
 * This is an autogenerated class - do not edit
 * 
 */
public interface OriginRealm extends Avp<DiameterIdentity> {

    int CODE = 296;

    
    static OriginRealm of(final Buffer value) {
        final DiameterIdentity v = DiameterIdentity.parse(value);
        return of(v);
    }

    static OriginRealm of(final String value) {
        return of(Buffers.wrap(value));
    }

    static OriginRealm of(final DiameterIdentity value) {
        assertNotNull(value);
        final Builder<DiameterIdentity> builder =
                Avp.ofType(DiameterIdentity.class)
                        .withValue(value)
                        .withAvpCode(CODE)
                        .isMandatory(AvpMandatory.MUST.isMandatory())
                        .isProtected(AvpProtected.MUST_NOT.isProtected())
                        .withVendor(Vendor.NONE);

        return new DefaultOriginRealm(builder.build());
    }

    

    @Override
    default long getCode() {
        return CODE;
    }

    default boolean isOriginRealm() {
        return true;
    }

    default OriginRealm toOriginRealm() {
        return this;
    }

    static OriginRealm parse(final FramedAvp raw) {
        if (CODE != raw.getCode()) {
            throw new AvpParseException("AVP Code mismatch - unable to parse the AVP into a " + OriginRealm.class.getName());
        }
        return new DefaultOriginRealm(raw);
    }

    class DefaultOriginRealm extends DiameterIdentityAvp implements OriginRealm {
        private DefaultOriginRealm(final FramedAvp raw) {
            super(raw);
        }

        @Override
        public OriginRealm ensure() {
            return this;
        }

        @Override
        public boolean equals(final Object other) {
            if (this == other) {
                return true;
            }

            if (other == null) {
                return false;
            }

            try {
                final OriginRealm o = (OriginRealm)other;
                final DiameterIdentity v = getValue();
                return v.equals(o.getValue());
            } catch (final ClassCastException e) {
                return false;
            }
        }
    }
}
