package io.snice.networking.codec.diameter.avp.api;


import io.snice.buffer.Buffer;
import io.snice.buffer.Buffers; 
import io.snice.networking.codec.diameter.avp.Avp;
import io.snice.networking.codec.diameter.avp.AvpMandatory;
import io.snice.networking.codec.diameter.avp.AvpParseException;
import io.snice.networking.codec.diameter.avp.AvpProtected;
import io.snice.networking.codec.diameter.avp.FramedAvp;
import io.snice.networking.codec.diameter.avp.Vendor;

import static io.snice.preconditions.PreConditions.assertNotNull;
import java.util.List;
import java.util.Optional;

import io.snice.networking.codec.diameter.avp.impl.DiameterUtf8StringAvp;
import io.snice.networking.codec.diameter.avp.type.UTF8String;

/**
 * This is an autogenerated class - do not edit
 * 
 */
public interface ProductName extends Avp<UTF8String> {

    int CODE = 269;

    
    static ProductName of(final Buffer value) {
        final UTF8String v = UTF8String.parse(value);
        return of(v);
    }

    static ProductName of(final String value) {
        return of(Buffers.wrap(value));
    }

    
    

    static ProductName of(final UTF8String value) {
        assertNotNull(value);
        final Builder<UTF8String> builder =
                Avp.ofType(UTF8String.class)
                        .withValue(value)
                        .withAvpCode(CODE)
                        .isMandatory(AvpMandatory.MUST_NOT.isMandatory())
                        .isProtected(AvpProtected.MUST_NOT.isProtected())
                        .withVendor(Vendor.NONE);

        return new DefaultProductName(builder.build());
    }

    @Override
    default long getCode() {
        return CODE;
    }

    default boolean isProductName() {
        return true;
    }

    default ProductName toProductName() {
        return this;
    }

    static ProductName parse(final FramedAvp raw) {
        if (CODE != raw.getCode()) {
            throw new AvpParseException("AVP Code mismatch - unable to parse the AVP into a " + ProductName.class.getName());
        }
        return new DefaultProductName(raw);
    }

    class DefaultProductName extends DiameterUtf8StringAvp implements ProductName {
        private DefaultProductName(final FramedAvp raw) {
            super(raw);
        }

        @Override
        public ProductName ensure() {
            return this;
        }

        @Override
        public boolean equals(final Object other) {
            if (this == other) {
                return true;
            }

            if (other == null) {
                return false;
            }

            try {
                final ProductName o = (ProductName)((FramedAvp)other).ensure();
                final UTF8String v = getValue();
                return v.equals(o.getValue());
            } catch (final ClassCastException e) {
                return false;
            }
        }
    }
}
