package io.snice.networking.codec.diameter.avp.api;


import io.snice.buffer.Buffer;
import io.snice.buffer.Buffers; 
import io.snice.networking.codec.diameter.avp.Avp;
import io.snice.networking.codec.diameter.avp.AvpMandatory;
import io.snice.networking.codec.diameter.avp.AvpParseException;
import io.snice.networking.codec.diameter.avp.AvpProtected;
import io.snice.networking.codec.diameter.avp.FramedAvp;
import io.snice.networking.codec.diameter.avp.Vendor;

import static io.snice.preconditions.PreConditions.assertNotNull;
import java.util.List;
import java.util.Optional;

import io.snice.networking.codec.diameter.avp.impl.DiameterOctetStringAvp;
import io.snice.networking.codec.diameter.avp.type.OctetString;

/**
 * This is an autogenerated class - do not edit
 * 
 */
public interface VisitedPlmnId extends Avp<OctetString> {

    int CODE = 1407;

    
    static VisitedPlmnId of(final Buffer value) {
        final OctetString v = OctetString.parse(value);
        return of(v);
    }

    static VisitedPlmnId of(final String value) {
        return of(Buffers.wrap(value));
    }

    
    

    static VisitedPlmnId of(final OctetString value) {
        assertNotNull(value);
        final Builder<OctetString> builder =
                Avp.ofType(OctetString.class)
                        .withValue(value)
                        .withAvpCode(CODE)
                        .isMandatory(AvpMandatory.MUST.isMandatory())
                        .isProtected(AvpProtected.MAY.isProtected())
                        .withVendor(Vendor.TGPP);

        return new DefaultVisitedPlmnId(builder.build());
    }

    @Override
    default long getCode() {
        return CODE;
    }

    default boolean isVisitedPlmnId() {
        return true;
    }

    default VisitedPlmnId toVisitedPlmnId() {
        return this;
    }

    static VisitedPlmnId parse(final FramedAvp raw) {
        if (CODE != raw.getCode()) {
            throw new AvpParseException("AVP Code mismatch - unable to parse the AVP into a " + VisitedPlmnId.class.getName());
        }
        return new DefaultVisitedPlmnId(raw);
    }

    class DefaultVisitedPlmnId extends DiameterOctetStringAvp implements VisitedPlmnId {
        private DefaultVisitedPlmnId(final FramedAvp raw) {
            super(raw);
        }

        @Override
        public VisitedPlmnId ensure() {
            return this;
        }

        @Override
        public boolean equals(final Object other) {
            if (this == other) {
                return true;
            }

            if (other == null) {
                return false;
            }

            try {
                final VisitedPlmnId o = (VisitedPlmnId)((FramedAvp)other).ensure();
                final OctetString v = getValue();
                return v.equals(o.getValue());
            } catch (final ClassCastException e) {
                return false;
            }
        }
    }
}
